from django.core.management.base import BaseCommand
from core.models import Course, Lesson, Achievement

class Command(BaseCommand):
    help = 'Seeds TypeForge curriculum with 13 progressive stages, 54 lessons, teacher modules, and spaced repetition'

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding TypeForge pedagogical curriculum..."))

        course, _ = Course.objects.get_or_create(
            slug='touch-typing-mastery',
            defaults={
                'title': 'Touch Typing Mastery',
                'description': 'Master touch typing step-by-step from home row foundation to advanced speed and precision.',
                'icon': 'keyboard',
                'order': 1
            }
        )

        # 54 comprehensive progressive lessons with teacher explanations and spaced repetition
        lessons_data = [
            # LEVEL 1: FOUNDATION (Lessons 1 - 4)
            {
                'level_number': 1,
                'stage': 'foundation',
                'level_title': 'Stage 1: Foundation & Posture',
                'lesson_number': 1,
                'title': 'The F and J Guide Bumps',
                'slug': 'intro-home-row',
                'key_name': 'F and J Keys',
                'target_finger': 'Left Index (F) & Right Index (J)',
                'finger_hand': 'Both Hands (Index Fingers)',
                'finger_why': 'F and J are your home anchor points. They feature small tactile bumps that allow your hands to find the home position without looking down at the keyboard.',
                'skill_learned': 'Locating tactile guide bumps and anchoring index fingers on the home row.',
                'spaced_repetition_keys': 'f, j',
                'learning_objective': 'Goal: Locate the F and J bumps using your index fingers and type single-key repetitions with relaxed posture.',
                'instruction': 'Rest your left index finger lightly on F and right index on J. Feel the small raised bump. Press each key smoothly without looking down.',
                'target_text': 'f f f f j j j j ff ff jj jj f f j j ff jj',
                'keys_introduced': 'f, j',
                'min_wpm_3stars': 10,
                'min_wpm_4stars': 18,
                'min_wpm_5stars': 25,
            },
            {
                'level_number': 1,
                'stage': 'foundation',
                'level_title': 'Stage 1: Foundation & Posture',
                'lesson_number': 2,
                'title': 'Alternating Index Pairs',
                'slug': 'f-and-j-keys',
                'key_name': 'F & J Alternating Pairs',
                'target_finger': 'Left Index & Right Index',
                'finger_hand': 'Both Hands (Index Fingers)',
                'finger_why': 'Alternating between hands teaches your brain independence between left and right motor cortices.',
                'skill_learned': 'Alternating bilateral strikes with consistent finger heights.',
                'spaced_repetition_keys': 'f, j',
                'learning_objective': 'Goal: Build a steady alternating rhythm between left and right index fingers.',
                'instruction': 'Strike F with left index, J with right index. Keep wrists hovering gently above the desk.',
                'target_text': 'fj jf fj jf ff jj fj jf ff jj fj jf jf fj',
                'keys_introduced': 'f, j',
                'min_wpm_3stars': 12,
                'min_wpm_4stars': 20,
                'min_wpm_5stars': 28,
            },
            {
                'level_number': 1,
                'stage': 'foundation',
                'level_title': 'Stage 1: Foundation & Posture',
                'lesson_number': 3,
                'title': 'Cadence & Rhythm Drill',
                'slug': 'alternating-f-and-j',
                'key_name': 'Rhythm & Cadence',
                'target_finger': 'Left Index & Right Index',
                'finger_hand': 'Both Hands',
                'finger_why': 'Consistent metronome-like timing is 3x more effective for muscle memory than sporadic fast bursts.',
                'skill_learned': 'Even timing cadence without pausing or looking down.',
                'spaced_repetition_keys': 'f, j',
                'learning_objective': 'Goal: Establish an even, clock-like typing beat. Prioritize 100% accuracy.',
                'instruction': 'Maintain a steady, relaxed beat. Every tap should have identical force and sound.',
                'target_text': 'f f j j f j f j j f j f ff jj jf fj ff jj',
                'keys_introduced': 'f, j',
                'min_wpm_3stars': 14,
                'min_wpm_4stars': 22,
                'min_wpm_5stars': 30,
            },
            {
                'level_number': 1,
                'stage': 'foundation',
                'level_title': 'Stage 1: Foundation & Posture',
                'lesson_number': 4,
                'title': 'The Space Bar Integration',
                'slug': 'the-space-bar',
                'key_name': 'Space Bar',
                'target_finger': 'Thumbs (Right or Left)',
                'finger_hand': 'Dominant Thumb',
                'finger_why': 'Thumbs naturally rest directly over the space bar. Use a gentle tap with your right thumb (or left) without shifting your palm.',
                'skill_learned': 'Integrating the space bar smoothly without displacing home row anchor fingers.',
                'spaced_repetition_keys': 'f, j, space',
                'learning_objective': 'Goal: Tap the space bar lightly with your thumb between words without disrupting your home position.',
                'instruction': 'Tap the space bar with your thumb, then return to resting position. Do not slap the key.',
                'target_text': 'f j f j fj jf ff jj j j f f fj jf f j f j',
                'keys_introduced': 'space',
                'min_wpm_3stars': 15,
                'min_wpm_4stars': 24,
                'min_wpm_5stars': 32,
            },

            # LEVEL 2: HOME ROW (Lessons 5 - 10)
            {
                'level_number': 2,
                'stage': 'home_row',
                'level_title': 'Stage 2: Home Row Mastery',
                'lesson_number': 5,
                'title': 'D and K (Middle Fingers)',
                'slug': 'd-and-k-keys',
                'key_name': 'D and K Keys',
                'target_finger': 'Left Middle (D) & Right Middle (K)',
                'finger_hand': 'Both Hands (Middle Fingers)',
                'finger_why': 'Middle fingers are longer and naturally rest on D and K next to your index anchor fingers.',
                'skill_learned': 'Middle finger muscle memory and index-middle coordination.',
                'spaced_repetition_keys': 'f, j, space, d, k',
                'learning_objective': 'Goal: Master D with left middle finger and K with right middle finger while maintaining F/J anchors.',
                'instruction': 'Left middle finger strikes D. Right middle finger strikes K. Keep index fingers floating above F and J.',
                'target_text': 'd d d d k k k k dd kk df jk kd fd dk kd fk jd',
                'keys_introduced': 'd, k',
                'min_wpm_3stars': 15,
                'min_wpm_4stars': 24,
                'min_wpm_5stars': 32,
            },
            {
                'level_number': 2,
                'stage': 'home_row',
                'level_title': 'Stage 2: Home Row Mastery',
                'lesson_number': 6,
                'title': 'F, J, D, and K Combinations',
                'slug': 'f-j-d-k-combos',
                'key_name': 'Bilateral Home Combos',
                'target_finger': 'Left Index/Middle & Right Index/Middle',
                'finger_hand': 'Both Hands',
                'finger_why': 'Cross-hand transitions between index and middle fingers create the core foundation for touch typing.',
                'skill_learned': 'Coordinating 4 home keys across both hands with spaced repetition.',
                'spaced_repetition_keys': 'f, j, d, k',
                'learning_objective': 'Goal: Build fluid transitions between all 4 central home row keys (F, J, D, K).',
                'instruction': 'Curve your fingers naturally like holding a baseball. Strike downward with fingertips.',
                'target_text': 'kfd jdf djk fkd dff kjj ddk kkf jfd kdf djk',
                'keys_introduced': 'd, k, f, j',
                'min_wpm_3stars': 16,
                'min_wpm_4stars': 25,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 2,
                'stage': 'home_row',
                'level_title': 'Stage 2: Home Row Mastery',
                'lesson_number': 7,
                'title': 'S and L (Ring Fingers)',
                'slug': 's-and-l-keys',
                'key_name': 'S and L Keys',
                'target_finger': 'Left Ring (S) & Right Ring (L)',
                'finger_hand': 'Both Hands (Ring Fingers)',
                'finger_why': 'Ring fingers share a tendon with middle fingers and require deliberate practice to develop independence.',
                'skill_learned': 'Ring finger isolation and coordination with index and middle fingers.',
                'spaced_repetition_keys': 'f, j, d, k, s, l',
                'learning_objective': 'Goal: Develop independent ring finger motor control on S and L without rotating your wrists.',
                'instruction': 'Use left ring finger for S and right ring finger for L. Keep palms steady.',
                'target_text': 's s s s l l l l sl ls ss ll sk dl ls sl as df jk l;',
                'keys_introduced': 's, l',
                'min_wpm_3stars': 16,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 2,
                'stage': 'home_row',
                'level_title': 'Stage 2: Home Row Mastery',
                'lesson_number': 8,
                'title': 'A and Semicolon (Pinky Fingers)',
                'slug': 'a-and-semicolon',
                'key_name': 'A and Semicolon Keys',
                'target_finger': 'Left Pinky (A) & Right Pinky (;)',
                'finger_hand': 'Both Hands (Pinky Fingers)',
                'finger_why': 'Pinky fingers guard the outer perimeters of the keyboard. They strike A and ; while keeping your hand relaxed.',
                'skill_learned': 'Pinky finger extension without tilting wrists outward.',
                'spaced_repetition_keys': 'f, j, d, k, s, l, a, ;',
                'learning_objective': 'Goal: Strike A with left pinky and ; with right pinky, completing full home row coverage.',
                'instruction': 'Left pinky on A, right pinky on semicolon (;). Do not rotate your wrists outward.',
                'target_text': 'a a a a ; ; ; ; a; ;a aa ;; as df jk l; a; fa ja ;a',
                'keys_introduced': 'a, ;',
                'min_wpm_3stars': 16,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 2,
                'stage': 'home_row',
                'level_title': 'Stage 2: Home Row Mastery',
                'lesson_number': 9,
                'title': 'Home Row Complete Flow',
                'slug': 'home-row-flow',
                'key_name': 'Full Home Row',
                'target_finger': 'All 8 Fingers + Thumbs',
                'finger_hand': 'Both Hands',
                'finger_why': 'All 8 fingers now rest on their permanent home row positions: A S D F and J K L ;',
                'skill_learned': 'Simultaneous 8-finger tactile coordination across the home row.',
                'spaced_repetition_keys': 'a, s, d, f, j, k, l, ;, space',
                'learning_objective': 'Goal: Flow effortlessly across all 8 home row keys with zero glances at the keyboard.',
                'instruction': 'All fingers are active. Focus on relaxed shoulders and fluid strikes.',
                'target_text': 'asdf jkl; asdf jkl; a s d f j k l ; sad lad fad ask all',
                'keys_introduced': 'a, s, d, f, j, k, l, ;',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },
            {
                'level_number': 2,
                'stage': 'home_row',
                'level_title': 'Stage 2: Home Row Mastery',
                'lesson_number': 10,
                'title': 'Home Row Real Words',
                'slug': 'home-row-words',
                'key_name': 'Home Row Vocabulary',
                'target_finger': 'All 8 Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Typing real words converts letter-by-letter conscious effort into subconscious whole-word motor chords.',
                'skill_learned': 'Whole-word muscle memory chunking.',
                'spaced_repetition_keys': 'a, s, d, f, j, k, l',
                'learning_objective': 'Goal: Type real English words formed exclusively from the home row without pausing.',
                'instruction': 'Look at the whole word, visualize the fingers striking in order, then type the sequence.',
                'target_text': 'ask all fall lad dad sad flask salad salsa flash falls alas',
                'keys_introduced': 'home row words',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },

            # LEVEL 3: TOP ROW (Lessons 11 - 16)
            {
                'level_number': 3,
                'stage': 'top_row',
                'level_title': 'Stage 3: Top Row',
                'lesson_number': 11,
                'title': 'G and H (Inner Index Reaches)',
                'slug': 'g-and-h-keys',
                'key_name': 'G and H Keys',
                'target_finger': 'Left Index (G) & Right Index (H)',
                'finger_hand': 'Both Hands (Index Reaches)',
                'finger_why': 'G and H sit directly between F and J. Reach inward with index fingers and immediately snap back to home.',
                'skill_learned': 'Inward lateral reach and immediate snapback to home bumps.',
                'spaced_repetition_keys': 'f, j, g, h, a, s, d, k, l',
                'learning_objective': 'Goal: Reach inward to G with left index and H with right index, then snap back to F and J.',
                'instruction': 'Stretch index fingers toward the center for G and H, then immediately snap back.',
                'target_text': 'fg hj gf jh gg hh fg hj glad half flag shaft dash fad had',
                'keys_introduced': 'g, h',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },
            {
                'level_number': 3,
                'stage': 'top_row',
                'level_title': 'Stage 3: Top Row',
                'lesson_number': 12,
                'title': 'R and U (Index Reaches Up)',
                'slug': 'r-and-u-keys',
                'key_name': 'R and U Keys',
                'target_finger': 'Left Index (R) & Right Index (U)',
                'finger_hand': 'Both Hands (Index Up)',
                'finger_why': 'R is directly above F; U is directly above J. Extend forward from your home anchor without moving your wrist.',
                'skill_learned': 'Vertical upward reach with index fingers.',
                'spaced_repetition_keys': 'f, j, r, u, d, k, s, l, a',
                'learning_objective': 'Goal: Reach up from F to R and J to U, integrating two of the most frequent English letters.',
                'instruction': 'Extend index finger upward to R and U. Return immediately to home bumps.',
                'target_text': 'fr ju rf uj rr uu fur jug jar run rug rust dust surf guard',
                'keys_introduced': 'r, u',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'stage': 'top_row',
                'level_title': 'Stage 3: Top Row',
                'lesson_number': 13,
                'title': 'E and I (Middle Reaches Up)',
                'slug': 'e-and-i-keys',
                'key_name': 'E and I Keys',
                'target_finger': 'Left Middle (E) & Right Middle (I)',
                'finger_hand': 'Both Hands (Middle Up)',
                'finger_why': 'E is the single most common letter in the English language! D reaches to E, K reaches to I.',
                'skill_learned': 'Vertical middle finger reaches for high-frequency vowels.',
                'spaced_repetition_keys': 'e, i, d, k, f, j, r, u, a, s',
                'learning_objective': 'Goal: Master the high-frequency vowel reaches: D to E and K to I.',
                'instruction': 'Reach left middle up from D to E, and right middle up from K to I.',
                'target_text': 'de ki ed ik ee ii ride side like fire hide life deer risk side',
                'keys_introduced': 'e, i',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'stage': 'top_row',
                'level_title': 'Stage 3: Top Row',
                'lesson_number': 14,
                'title': 'W and O (Ring Reaches Up)',
                'slug': 'w-and-o-keys',
                'key_name': 'W and O Keys',
                'target_finger': 'Left Ring (W) & Right Ring (O)',
                'finger_hand': 'Both Hands (Ring Up)',
                'finger_why': 'S reaches up to W, L reaches up to O. Keep other fingers anchored so you do not lose position.',
                'skill_learned': 'Upward ring finger trajectory while stabilizing adjacent fingers.',
                'spaced_repetition_keys': 'w, o, s, l, e, i, r, u, f, j',
                'learning_objective': 'Goal: Reach up from S to W and L to O with ring fingers smoothly.',
                'instruction': 'Extend ring fingers up from S to W and L to O.',
                'target_text': 'sw lo ws ol ww oo show slow wolf wood word flow work good',
                'keys_introduced': 'w, o',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'stage': 'top_row',
                'level_title': 'Stage 3: Top Row',
                'lesson_number': 15,
                'title': 'Q and P (Pinky Reaches Up)',
                'slug': 'q-and-p-keys',
                'key_name': 'Q and P Keys',
                'target_finger': 'Left Pinky (Q) & Right Pinky (P)',
                'finger_hand': 'Both Hands (Pinky Up)',
                'finger_why': 'A reaches up to Q, ; reaches up to P. Pinky reaches require careful control so the hand does not twist.',
                'skill_learned': 'Upper corner pinky extension with zero wrist twist.',
                'spaced_repetition_keys': 'q, p, a, ;, w, o, e, i, r, u',
                'learning_objective': 'Goal: Extend pinky fingers upward to Q and P without shifting your entire palm off the home row.',
                'instruction': 'Reach left pinky up to Q, right pinky up to P. Snap back to A and ; immediately.',
                'target_text': 'aq ;p qa p; qq pp equip quote paper power quick park proud',
                'keys_introduced': 'q, p',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'stage': 'top_row',
                'level_title': 'Stage 3: Top Row',
                'lesson_number': 16,
                'title': 'Top Row Words & Integration',
                'slug': 'top-row-words',
                'key_name': 'Top Row Synthesis',
                'target_finger': 'All 8 Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Combining top row with home row unlocks thousands of English words.',
                'skill_learned': 'Multi-row vertical fluid transitions.',
                'spaced_repetition_keys': 'all home and top row keys',
                'learning_objective': 'Goal: Seamlessly integrate home row and top row letters across varied vocabulary.',
                'instruction': 'Flow between top row and home row without hesitation.',
                'target_text': 'pure quiet pride tower write water power guide report sleep',
                'keys_introduced': 'q, w, e, r, t, y, u, i, o, p',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },

            # LEVEL 4: BOTTOM ROW (Lessons 17 - 21)
            {
                'level_number': 4,
                'stage': 'bottom_row',
                'level_title': 'Stage 4: Bottom Row',
                'lesson_number': 17,
                'title': 'V and M (Index Reaches Down)',
                'slug': 'v-and-m-keys',
                'key_name': 'V and M Keys',
                'target_finger': 'Left Index (V) & Right Index (M)',
                'finger_hand': 'Both Hands (Index Down)',
                'finger_why': 'F drops down to V, J drops down to M. Curl your index fingers inward and down.',
                'skill_learned': 'Downward index finger curling with immediate return to home.',
                'spaced_repetition_keys': 'v, m, f, j, r, u, e, i, d, k',
                'learning_objective': 'Goal: Reach downward from F to V and J to M without losing your home position.',
                'instruction': 'Curl left index down to V, right index down to M.',
                'target_text': 'fv jm vf mj vv mm vine move view move voice vim form norm',
                'keys_introduced': 'v, m',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'stage': 'bottom_row',
                'level_title': 'Stage 4: Bottom Row',
                'lesson_number': 18,
                'title': 'C and Comma (Middle Reaches Down)',
                'slug': 'c-and-comma',
                'key_name': 'C and Comma Keys',
                'target_finger': 'Left Middle (C) & Right Middle (,)',
                'finger_hand': 'Both Hands (Middle Down)',
                'finger_why': 'D curls down to C, K curls down to comma (,). Maintain index anchors on F and J.',
                'skill_learned': 'Downward middle finger curl and punctuation integration.',
                'spaced_repetition_keys': 'c, ,, d, k, v, m, e, i',
                'learning_objective': 'Goal: Master downward middle finger strikes for C and comma (,).',
                'instruction': 'Curl left middle down to C and right middle down to comma (,).',
                'target_text': 'dc k, cd ,k cc ,, come, call, calm, cool, camp, code, pace,',
                'keys_introduced': 'c, ,',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'stage': 'bottom_row',
                'level_title': 'Stage 4: Bottom Row',
                'lesson_number': 19,
                'title': 'X and Period (Ring Reaches Down)',
                'slug': 'x-and-period',
                'key_name': 'X and Period Keys',
                'target_finger': 'Left Ring (X) & Right Ring (.)',
                'finger_hand': 'Both Hands (Ring Down)',
                'finger_why': 'S curls down to X, L curls down to period (.). Periods finish every thought in writing.',
                'skill_learned': 'Downward ring finger dexterity and sentence punctuation.',
                'spaced_repetition_keys': 'x, ., s, l, c, ,, w, o',
                'learning_objective': 'Goal: Reach down from S to X and L to period (.) with relaxed ring fingers.',
                'instruction': 'Curl left ring finger down to X, right ring finger down to period (.).',
                'target_text': 'sx l. xs .l xx .. exact. exam. extra. next. text. fix. mix.',
                'keys_introduced': 'x, .',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'stage': 'bottom_row',
                'level_title': 'Stage 4: Bottom Row',
                'lesson_number': 20,
                'title': 'Z and Slash (Pinky Reaches Down)',
                'slug': 'z-and-slash',
                'key_name': 'Z and Slash Keys',
                'target_finger': 'Left Pinky (Z) & Right Pinky (/)',
                'finger_hand': 'Both Hands (Pinky Down)',
                'finger_why': 'A curls down to Z, ; curls down to slash (/). Pinkies control the lower keyboard boundaries.',
                'skill_learned': 'Lower corner pinky control.',
                'spaced_repetition_keys': 'z, /, a, ;, x, ., c, ,, v, m',
                'learning_objective': 'Goal: Curl left pinky down to Z and right pinky down to slash (/).',
                'instruction': 'Drop left pinky to Z, right pinky to slash (/). Snap back immediately.',
                'target_text': 'az ;/ za /; zz // zero/zone jazz/zoom zinc/zeal size/maze',
                'keys_introduced': 'z, /',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'stage': 'bottom_row',
                'level_title': 'Stage 4: Bottom Row',
                'lesson_number': 21,
                'title': 'Bottom Row Integration',
                'slug': 'bottom-row-integration',
                'key_name': 'Bottom Row Synthesis',
                'target_finger': 'All 8 Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Full three-row freedom: home row, top row, and bottom row combined.',
                'skill_learned': '3-row vertical synthesis and punctuation control.',
                'spaced_repetition_keys': 'all alphabet and punctuation',
                'learning_objective': 'Goal: Combine bottom row keys with home row and top row smoothly.',
                'instruction': 'Type complete sentences using punctuation and bottom row letters.',
                'target_text': 'vocal calm exact zone. move quick, view text, zinc maze.',
                'keys_introduced': 'z, x, c, v, m, ,, ., /',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },

            # LEVEL 5: FULL ALPHABET (Lessons 22 - 25)
            {
                'level_number': 5,
                'stage': 'full_alphabet',
                'level_title': 'Stage 5: Full Alphabet Integration',
                'lesson_number': 22,
                'title': 'Every Letter Connected',
                'slug': 'every-letter-connected',
                'key_name': 'Full Alphabet Pangrams',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Pangrams exercise every finger and neural pathway across all 26 letters.',
                'skill_learned': 'Comprehensive 26-letter muscle memory connectivity.',
                'spaced_repetition_keys': 'all 26 letters',
                'learning_objective': 'Goal: Flow effortlessly across all 26 letters of the English alphabet.',
                'instruction': 'Maintain a steady typing pace. Do not look down at the keyboard.',
                'target_text': 'the quick brown fox jumps over a lazy dog while walking near',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 24,
                'min_wpm_4stars': 34,
                'min_wpm_5stars': 45,
            },
            {
                'level_number': 5,
                'stage': 'full_alphabet',
                'level_title': 'Stage 5: Full Alphabet Integration',
                'lesson_number': 23,
                'title': 'Pangram Precision',
                'slug': 'pangram-precision',
                'key_name': 'Dexterity Pangrams',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Strengthens uncommon letter pairs (like qu, dz, ck, ly).',
                'skill_learned': 'Uncommon letter transition fluidity.',
                'spaced_repetition_keys': 'all 26 letters',
                'learning_objective': 'Goal: Maintain high precision on uncommon English letter combinations.',
                'instruction': 'Read words in full before striking.',
                'target_text': 'pack my box with five dozen liquor jugs and cozy warm blankets',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 25,
                'min_wpm_4stars': 35,
                'min_wpm_5stars': 46,
            },
            {
                'level_number': 5,
                'stage': 'full_alphabet',
                'level_title': 'Stage 5: Full Alphabet Integration',
                'lesson_number': 24,
                'title': 'Alphabet Speed Flow',
                'slug': 'alphabet-speed-flow',
                'key_name': 'Fluidity Drills',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Building consistent speed across complex syllable structures.',
                'skill_learned': 'Rhythmic speed stability.',
                'spaced_repetition_keys': 'all 26 letters',
                'learning_objective': 'Goal: Build fluid velocity across all 26 letters of the alphabet.',
                'instruction': 'Relax muscles and maintain consistent cadence.',
                'target_text': 'how vexingly quick daft zebras jump through foggy twilight skies',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 26,
                'min_wpm_4stars': 36,
                'min_wpm_5stars': 48,
            },
            {
                'level_number': 5,
                'stage': 'full_alphabet',
                'level_title': 'Stage 5: Full Alphabet Integration',
                'lesson_number': 25,
                'title': 'Full Alphabet Milestone',
                'slug': 'alphabet-milestone',
                'key_name': 'Alphabet Capstone',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Proves complete coverage of all 26 letters with high accuracy.',
                'skill_learned': 'Complete alphabet touch-typing independence.',
                'spaced_repetition_keys': 'all 26 letters',
                'learning_objective': 'Goal: Demonstrate complete touch typing independence across the entire alphabet.',
                'instruction': 'Test your complete keyboard coverage without stopping.',
                'target_text': 'bright vixens jump safely with quiet quick zeal and nimble grace',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 28,
                'min_wpm_4stars': 38,
                'min_wpm_5stars': 50,
            },

            # LEVEL 6: CAPITAL LETTERS & SHIFT (Lessons 26 - 29)
            {
                'level_number': 6,
                'stage': 'capital_letters',
                'level_title': 'Stage 6: Capital Letters & Shift Keys',
                'lesson_number': 26,
                'title': 'Right Shift with Left Hand Keys',
                'slug': 'right-shift-left-hand',
                'key_name': 'Right Shift Key',
                'target_finger': 'Right Pinky (Shift) + Left Hand Letter',
                'finger_hand': 'Opposite Hands (Shift Rule)',
                'finger_why': 'The golden rule of shift: ALWAYS hold Shift with the opposite hand of the letter you are typing.',
                'skill_learned': 'Opposite-hand Shift key coordination.',
                'spaced_repetition_keys': 'Shift, all left hand keys',
                'learning_objective': 'Goal: Hold Right Shift with right pinky while striking left-hand capital letters.',
                'instruction': 'Press and hold Right Shift with right pinky, strike the letter with left hand, release Shift.',
                'target_text': 'Fast Deer Slow Fox Red Water Green Eagle Clean Quiet Travel',
                'keys_introduced': 'Right Shift',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },
            {
                'level_number': 6,
                'stage': 'capital_letters',
                'level_title': 'Stage 6: Capital Letters & Shift Keys',
                'lesson_number': 27,
                'title': 'Left Shift with Right Hand Keys',
                'slug': 'left-shift-right-hand',
                'key_name': 'Left Shift Key',
                'target_finger': 'Left Pinky (Shift) + Right Hand Letter',
                'finger_hand': 'Opposite Hands (Shift Rule)',
                'finger_why': 'Hold Left Shift with left pinky when typing right-hand capital letters (J, K, L, U, I, O, P, H, N, M).',
                'skill_learned': 'Bilateral Shift alternation.',
                'spaced_repetition_keys': 'Left Shift, all right hand keys',
                'learning_objective': 'Goal: Hold Left Shift with left pinky while striking right-hand capital letters.',
                'instruction': 'Hold Left Shift with left pinky, strike the letter with right hand, release Shift.',
                'target_text': 'Jump Kite Lake Moon Hope Peak Night Island Yellow Olive Path',
                'keys_introduced': 'Left Shift',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },
            {
                'level_number': 6,
                'stage': 'capital_letters',
                'level_title': 'Stage 6: Capital Letters & Shift Keys',
                'lesson_number': 28,
                'title': 'Proper Names & Cities',
                'slug': 'proper-names-cities',
                'key_name': 'Shift Alternation',
                'target_finger': 'Both Pinkies (Alternating)',
                'finger_hand': 'Both Hands',
                'finger_why': 'Practicing capital letters across varied cities ensures automatic left/right shift selection.',
                'skill_learned': 'Automatic shift selection without mental latency.',
                'spaced_repetition_keys': 'Left Shift, Right Shift, capitals',
                'learning_objective': 'Goal: Alternate smoothly between left and right shift keys across capitalized proper nouns.',
                'instruction': 'Always choose the shift key on the opposite hand of the target letter.',
                'target_text': 'London, Paris, Tokyo, Berlin, Madrid, Chicago, Sydney, Oslo, Rome',
                'keys_introduced': 'Shift alternation',
                'min_wpm_3stars': 24,
                'min_wpm_4stars': 34,
                'min_wpm_5stars': 45,
            },
            {
                'level_number': 6,
                'stage': 'capital_letters',
                'level_title': 'Stage 6: Capital Letters & Shift Keys',
                'lesson_number': 29,
                'title': 'Capitalized Sentences',
                'slug': 'capitalized-sentences',
                'key_name': 'Sentence Starters',
                'target_finger': 'All Fingers + Shift',
                'finger_hand': 'Both Hands',
                'finger_why': 'Standard writing always begins with capitalized sentence starters and ends with periods.',
                'skill_learned': 'Sentence punctuation and capitalization flow.',
                'spaced_repetition_keys': 'Shift, punctuation, full alphabet',
                'learning_objective': 'Goal: Master natural capitalization and punctuation rhythm across full sentences.',
                'instruction': 'Strike the capital smoothly, then continue lowercase typing without breaking tempo.',
                'target_text': 'Every journey begins with a single step. Practice makes permanent.',
                'keys_introduced': 'Sentence capitalization',
                'min_wpm_3stars': 25,
                'min_wpm_4stars': 35,
                'min_wpm_5stars': 46,
            },

            # LEVEL 7: NUMBERS ROW (Lessons 30 - 32)
            {
                'level_number': 7,
                'stage': 'numbers',
                'level_title': 'Stage 7: Numbers Row',
                'lesson_number': 30,
                'title': 'Left Hand Numbers (1, 2, 3, 4, 5)',
                'slug': 'left-hand-numbers',
                'key_name': 'Numbers 1 - 5',
                'target_finger': 'Left Pinky (1), Ring (2), Middle (3), Index (4, 5)',
                'finger_hand': 'Left Hand',
                'finger_why': 'Reach up two rows from home keys. Pinky for 1, Ring for 2, Middle for 3, Index for 4 & 5.',
                'skill_learned': 'Left hand numeric reach and spatial awareness.',
                'spaced_repetition_keys': '1, 2, 3, 4, 5, a, s, d, f',
                'learning_objective': 'Goal: Reach up two rows with your left hand to strike numbers 1 through 5 accurately.',
                'instruction': 'Reach up from home row to numbers 1-5, then snap back to home.',
                'target_text': '1 2 3 4 5 12 34 51 25 43 15 24 35 123 451 234 521',
                'keys_introduced': '1, 2, 3, 4, 5',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 7,
                'stage': 'numbers',
                'level_title': 'Stage 7: Numbers Row',
                'lesson_number': 31,
                'title': 'Right Hand Numbers (6, 7, 8, 9, 0)',
                'slug': 'right-hand-numbers',
                'key_name': 'Numbers 6 - 0',
                'target_finger': 'Right Index (6, 7), Middle (8), Ring (9), Pinky (0)',
                'finger_hand': 'Right Hand',
                'finger_why': 'Reach up two rows with your right hand. Index reaches 6 and 7, Middle for 8, Ring for 9, Pinky for 0.',
                'skill_learned': 'Right hand numeric reach and zero anchor.',
                'spaced_repetition_keys': '6, 7, 8, 9, 0, j, k, l, ;',
                'learning_objective': 'Goal: Strike numbers 6 through 0 with designated right hand fingers.',
                'instruction': 'Reach up from J, K, L, ; to 6, 7, 8, 9, 0.',
                'target_text': '6 7 8 9 0 67 89 06 78 90 68 79 80 678 901 890 760',
                'keys_introduced': '6, 7, 8, 9, 0',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 7,
                'stage': 'numbers',
                'level_title': 'Stage 7: Numbers Row',
                'lesson_number': 32,
                'title': 'Numbers in Real Context',
                'slug': 'numbers-in-sentences',
                'key_name': 'Numbers & Dates Context',
                'target_finger': 'All Fingers + Numbers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Typing dates, years, and measurements seamlessly connects alphabet and numeric rows.',
                'skill_learned': 'Cross-row numeric transitions in real sentences.',
                'spaced_repetition_keys': '0-9, full alphabet, punctuation',
                'learning_objective': 'Goal: Transition smoothly between letters and numbers in realistic sentences.',
                'instruction': 'Keep your home anchors in your mind as you reach for numbers.',
                'target_text': 'In 1995 there were 32 computers, by 2024 there were over 870 devices.',
                'keys_introduced': 'numbers in context',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },

            # LEVEL 8: SYMBOLS & PUNCTUATION (Lessons 33 - 36)
            {
                'level_number': 8,
                'stage': 'symbols',
                'level_title': 'Stage 8: Symbols & Punctuation',
                'lesson_number': 33,
                'title': 'Exclamation and Question Marks',
                'slug': 'exclamation-and-question',
                'key_name': '! and ? Marks',
                'target_finger': 'Right Shift + 1 (!) and Left Shift + / (?)',
                'finger_hand': 'Opposite Hands (Shift)',
                'finger_why': '! is Right Shift + 1; ? is Left Shift + /. Crucial for questions and expressions.',
                'skill_learned': 'Shifted punctuation coordination.',
                'spaced_repetition_keys': '!, ?, capitals, alphabet',
                'learning_objective': 'Goal: Master exclamation marks (!) and question marks (?) without hesitation.',
                'instruction': 'Right Shift + 1 for !; Left Shift + / for ?.',
                'target_text': 'Hello! Is this working? Yes! Are you ready? Great! Let us start!',
                'keys_introduced': '!, ?',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 8,
                'stage': 'symbols',
                'level_title': 'Stage 8: Symbols & Punctuation',
                'lesson_number': 34,
                'title': 'Quotes and Apostrophes',
                'slug': 'quotes-and-apostrophes',
                'key_name': "Quotes & Apostrophes",
                'target_finger': "Right Pinky (Quote) & Left Shift + Quote",
                'finger_hand': "Right Pinky + Left Shift",
                'finger_why': "Apostrophes form English contractions (it's, don't, can't); Shift + ' creates dialogue quotes.",
                'skill_learned': 'Dialogue punctuation and contraction speed.',
                'spaced_repetition_keys': "\', \", alphabet",
                'learning_objective': "Goal: Type contractions and quotations with natural pinky fluidity.",
                'instruction': "Apostrophe is next to Enter with right pinky. Add Left Shift for double quotes.",
                'target_text': "She said, \"Do not worry, it\'s going to be fine.\" We can\'t stop now.",
                'keys_introduced': '\', "',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 8,
                'stage': 'symbols',
                'level_title': 'Stage 8: Symbols & Punctuation',
                'lesson_number': 35,
                'title': 'Brackets and Parentheses',
                'slug': 'brackets-and-parentheses',
                'key_name': 'Parentheses & Brackets',
                'target_finger': 'Shift + 9, 0 & Pinky Brackets',
                'finger_hand': 'Both Hands',
                'finger_why': 'Essential for code, mathematical notation, and scholarly prose.',
                'skill_learned': 'Enclosure symbol typing precision.',
                'spaced_repetition_keys': '(, ), [, ], {, }',
                'learning_objective': 'Goal: Type parentheses ( ) and brackets [ ] with accuracy.',
                'instruction': 'Left Shift + 9 and 0 for parentheses. Right pinky for brackets near P.',
                'target_text': 'The function calculate(x, y) returns [result] with options {fast: true}.',
                'keys_introduced': '(, ), [, ], {, }',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },
            {
                'level_number': 8,
                'stage': 'symbols',
                'level_title': 'Stage 8: Symbols & Punctuation',
                'lesson_number': 36,
                'title': 'Special Symbols & Math',
                'slug': 'special-symbols-math',
                'key_name': 'Math & Currency Symbols',
                'target_finger': 'Shifted Number Row',
                'finger_hand': 'Both Hands',
                'finger_why': 'Handle currency ($), percentages (%), email (@), and operators (+, =).',
                'skill_learned': 'Shifted upper symbol row fluency.',
                'spaced_repetition_keys': '@, #, $, %, &, *, +, =',
                'learning_objective': 'Goal: Type currency, email symbols, and mathematical operators accurately.',
                'instruction': 'Use Shift across the number row: @, #, $, %, &, *, +, =.',
                'target_text': 'Save 25% today! Contact user@example.com for $50 + $10 bonus.',
                'keys_introduced': '@, #, $, %, &, *, +, =',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },

            # LEVEL 9: COMMON WORDS (Lessons 37 - 40)
            {
                'level_number': 9,
                'stage': 'common_words',
                'level_title': 'Stage 9: High Frequency Words',
                'lesson_number': 37,
                'title': 'Top 25 English Words',
                'slug': 'top-25-words',
                'key_name': 'Core High-Frequency Words',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'These 25 words account for nearly 33% of all written English.',
                'skill_learned': 'Word-level motor chunking.',
                'spaced_repetition_keys': 'all alphabet, space',
                'learning_objective': 'Goal: Type the top 25 most frequent English words as automatic motor chords.',
                'instruction': 'Type entire words as single reflex chords.',
                'target_text': 'the of and a to in is you that it he was for on are as with his they at be this have from or',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 28,
                'min_wpm_4stars': 38,
                'min_wpm_5stars': 50,
            },
            {
                'level_number': 9,
                'stage': 'common_words',
                'level_title': 'Stage 9: High Frequency Words',
                'lesson_number': 38,
                'title': 'Words 26 through 50',
                'slug': 'words-26-to-50',
                'key_name': 'Words 26 - 50',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Common structural words (had, word, but, what, were, when, said).',
                'skill_learned': 'Structural word speed.',
                'spaced_repetition_keys': 'all alphabet',
                'learning_objective': 'Goal: Increase velocity through familiar structural word patterns.',
                'instruction': 'Notice letter groupings like "th", "ing", and "ed".',
                'target_text': 'one had by word but not what all were we when your can said there use an each which she do how their if will',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 30,
                'min_wpm_4stars': 40,
                'min_wpm_5stars': 52,
            },
            {
                'level_number': 9,
                'stage': 'common_words',
                'level_title': 'Stage 9: High Frequency Words',
                'lesson_number': 39,
                'title': 'Words 51 through 75',
                'slug': 'words-51-to-75',
                'key_name': 'Words 51 - 75',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Mid-tier vocabulary (other, about, many, these, some, would, make, like).',
                'skill_learned': 'Stamina on mid-tier words.',
                'spaced_repetition_keys': 'all alphabet',
                'learning_objective': 'Goal: Maintain high stamina across mid-frequency vocabulary.',
                'instruction': 'Keep a relaxed rhythm without pausing between words.',
                'target_text': 'up other about out many then them these so some her would make like him into time has look two more write go see',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 30,
                'min_wpm_4stars': 40,
                'min_wpm_5stars': 52,
            },
            {
                'level_number': 9,
                'stage': 'common_words',
                'level_title': 'Stage 9: High Frequency Words',
                'lesson_number': 40,
                'title': 'Words 76 through 100',
                'slug': 'words-76-to-100',
                'key_name': 'Words 76 - 100',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Completes the top 100 words which comprise over 50% of all written English.',
                'skill_learned': 'Full 100-word automation.',
                'spaced_repetition_keys': 'all alphabet',
                'learning_objective': 'Goal: Automate the final tier of the top 100 English words.',
                'instruction': 'Mastering these words unlocks unconscious touch typing.',
                'target_text': 'number no way could people my than first water been call who oil its now find long down day did get come made may part',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 32,
                'min_wpm_4stars': 42,
                'min_wpm_5stars': 55,
            },

            # LEVEL 10: SENTENCES & FLOW (Lessons 41 - 44)
            {
                'level_number': 10,
                'stage': 'sentences',
                'level_title': 'Stage 10: Sentences & Flow',
                'lesson_number': 41,
                'title': 'Conversational Sentences',
                'slug': 'conversational-sentences',
                'key_name': 'Conversational Cadence',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Transitions from isolated words to flowing complete grammatical thoughts.',
                'skill_learned': 'Thought-to-keystroke cadence.',
                'spaced_repetition_keys': 'full alphabet, shift, punctuation',
                'learning_objective': 'Goal: Read ahead of your fingers by two words while typing continuous thoughts.',
                'instruction': 'Read ahead of your fingers by two words.',
                'target_text': 'The sun rises in the east every morning. A cool breeze moved across the silent valley.',
                'keys_introduced': 'sentence flow',
                'min_wpm_3stars': 30,
                'min_wpm_4stars': 42,
                'min_wpm_5stars': 55,
            },
            {
                'level_number': 10,
                'stage': 'sentences',
                'level_title': 'Stage 10: Sentences & Flow',
                'lesson_number': 42,
                'title': 'Descriptive Observations',
                'slug': 'descriptive-observations',
                'key_name': 'Descriptive Prose',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Balances varied punctuation with vivid descriptive prose.',
                'skill_learned': 'Punctuation and capitalization balance.',
                'spaced_repetition_keys': 'commas, periods, capitals',
                'learning_objective': 'Goal: Maintain consistent tempo across commas, periods, and descriptive words.',
                'instruction': 'Stay focused on consistent tempo.',
                'target_text': 'Clear blue water flowed gently over the smooth river stones, reflecting the golden sunlight.',
                'keys_introduced': 'sentence flow',
                'min_wpm_3stars': 32,
                'min_wpm_4stars': 44,
                'min_wpm_5stars': 58,
            },
            {
                'level_number': 10,
                'stage': 'sentences',
                'level_title': 'Stage 10: Sentences & Flow',
                'lesson_number': 43,
                'title': 'Dialogue & Interrogatives',
                'slug': 'dialogue-interrogatives',
                'key_name': 'Dialogue Flow',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Mixes quotes, question marks, exclamation marks, and dialogue pacing.',
                'skill_learned': 'Dialogue and quote integration.',
                'spaced_repetition_keys': 'quotes, ?, !, capitals',
                'learning_objective': 'Goal: Type punctuated conversational dialogue with zero deceleration.',
                'instruction': 'Use correct pinky coordination for quotes.',
                'target_text': '"Where are we heading next?" asked Maya with a bright smile. "To the mountain peak!"',
                'keys_introduced': 'dialogue flow',
                'min_wpm_3stars': 32,
                'min_wpm_4stars': 44,
                'min_wpm_5stars': 58,
            },
            {
                'level_number': 10,
                'stage': 'sentences',
                'level_title': 'Stage 10: Sentences & Flow',
                'lesson_number': 44,
                'title': 'Continuous Thought Flow',
                'slug': 'continuous-thought-flow',
                'key_name': 'Endurance Flow',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Prevents cognitive fatigue when drafting longer arguments or ideas.',
                'skill_learned': 'Sustained typing endurance.',
                'spaced_repetition_keys': 'full keyboard',
                'learning_objective': 'Goal: Develop prolonged typing stamina without muscle tension or mental fatigue.',
                'instruction': 'Breathe steadily while typing longer passages.',
                'target_text': 'Curiosity drives discoveries that reshape the future, turning ambitious dreams into everyday reality.',
                'keys_introduced': 'sentence flow',
                'min_wpm_3stars': 34,
                'min_wpm_4stars': 46,
                'min_wpm_5stars': 60,
            },

            # LEVEL 11: PARAGRAPHS & LITERATURE (Lessons 45 - 48)
            {
                'level_number': 11,
                'stage': 'paragraphs',
                'level_title': 'Stage 11: Paragraphs & Literature',
                'lesson_number': 45,
                'title': 'The Craft of Writing',
                'slug': 'the-craft-of-writing',
                'key_name': 'Literary Craft',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Sustained long-form prose with rich vocabulary.',
                'skill_learned': 'Long-form stamina and pacing.',
                'spaced_repetition_keys': 'all keys',
                'learning_objective': 'Goal: Establish a sustainable cruising speed on multi-sentence literary prose.',
                'instruction': 'Do not rush early sentences. Establish a sustainable cruising speed.',
                'target_text': 'Writing is the painting of the voice. Through words, human beings bridge vast oceans of time and thought, sharing wisdom across generations with timeless clarity and emotional resonance.',
                'keys_introduced': 'paragraph flow',
                'min_wpm_3stars': 35,
                'min_wpm_4stars': 48,
                'min_wpm_5stars': 62,
            },
            {
                'level_number': 11,
                'stage': 'paragraphs',
                'level_title': 'Stage 11: Paragraphs & Literature',
                'lesson_number': 46,
                'title': 'Origins of the Keyboard',
                'slug': 'origins-of-the-keyboard',
                'key_name': 'Historical Prose',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Technical vocabulary with hyphenation and historical numbers.',
                'skill_learned': 'Technical prose fluency.',
                'spaced_repetition_keys': 'numbers, hyphens, capitals, alphabet',
                'learning_objective': 'Goal: Type informative technical history without breaking stride.',
                'instruction': 'Keep posture upright and shoulders relaxed.',
                'target_text': 'The QWERTY keyboard layout was engineered in the late nineteenth century to prevent mechanical typebars from colliding. Over a century later, touch typing remains the primary interface between human creativity and digital machines.',
                'keys_introduced': 'history prose',
                'min_wpm_3stars': 36,
                'min_wpm_4stars': 50,
                'min_wpm_5stars': 64,
            },
            {
                'level_number': 11,
                'stage': 'paragraphs',
                'level_title': 'Stage 11: Paragraphs & Literature',
                'lesson_number': 47,
                'title': 'Mountain Reflections',
                'slug': 'mountain-reflections',
                'key_name': 'Atmospheric Prose',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Varied punctuation cadence mimicking natural breath pauses.',
                'skill_learned': 'Expressive typing rhythm.',
                'spaced_repetition_keys': 'all punctuation and alphabet',
                'learning_objective': 'Goal: Observe how natural punctuation creates pauses in your typing rhythm.',
                'instruction': 'Observe how natural punctuation creates pauses in your typing rhythm.',
                'target_text': 'High above the treeline, alpine peaks caught the first rays of dawn. Cold winds whispered through ancient granite cliffs, while below, clouds drifted like soft waves over quiet valleys.',
                'keys_introduced': 'literary prose',
                'min_wpm_3stars': 36,
                'min_wpm_4stars': 50,
                'min_wpm_5stars': 65,
            },
            {
                'level_number': 11,
                'stage': 'paragraphs',
                'level_title': 'Stage 11: Paragraphs & Literature',
                'lesson_number': 48,
                'title': 'Deep Ocean Depths',
                'slug': 'deep-ocean-depths',
                'key_name': 'Scientific Prose',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Multi-syllable terms (bioluminescent, abyssal, navigating) requiring strict finger precision.',
                'skill_learned': 'Multi-syllabic finger agility.',
                'spaced_repetition_keys': 'full keyboard',
                'learning_objective': 'Goal: Maintain 98%+ accuracy across complex scientific vocabulary.',
                'instruction': 'Keep mistakes under control. Aim for 98%+ accuracy.',
                'target_text': 'Beneath the surface of the open sea lies a world of silence and wonder. Bioluminescent creatures glow in the abyssal darkness, navigating currents that have traveled around the globe for thousands of years.',
                'keys_introduced': 'science prose',
                'min_wpm_3stars': 38,
                'min_wpm_4stars': 52,
                'min_wpm_5stars': 68,
            },

            # LEVEL 12: SPEED TRAINING (Lessons 49 - 51)
            {
                'level_number': 12,
                'stage': 'speed_training',
                'level_title': 'Stage 12: Speed Training',
                'lesson_number': 49,
                'title': 'Velocity Sprint 1: Rapid Words',
                'slug': 'velocity-sprint-1',
                'key_name': 'High-Velocity Words',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Pushes your speed envelope on punchy, high-frequency vocabulary.',
                'skill_learned': 'Maximal burst velocity.',
                'spaced_repetition_keys': 'all alphabet',
                'learning_objective': 'Goal: Push your speed threshold on quick, punchy vocabulary without looking at keys.',
                'instruction': 'Let your fingers fly! Test your maximum raw speed.',
                'target_text': 'go fast run quick leap dash swift bolt sprint speed rush flash zoom drive fly glide soar blaze rocket surge dart race',
                'keys_introduced': 'speed sprint',
                'min_wpm_3stars': 42,
                'min_wpm_4stars': 58,
                'min_wpm_5stars': 75,
            },
            {
                'level_number': 12,
                'stage': 'speed_training',
                'level_title': 'Stage 12: Speed Training',
                'lesson_number': 50,
                'title': 'Velocity Sprint 2: High Cadence',
                'slug': 'velocity-sprint-2',
                'key_name': 'High-Cadence Flow',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Eliminates hesitation between space bars and word transitions.',
                'skill_learned': 'Continuous forward momentum.',
                'spaced_repetition_keys': 'all alphabet, commas',
                'learning_objective': 'Goal: Maintain rapid typing without hesitating on word transitions.',
                'instruction': 'Zero hesitation between space bars.',
                'target_text': 'rapid motion brings agile results when hands operate with confidence, clarity, and relentless forward determination.',
                'keys_introduced': 'speed sprint',
                'min_wpm_3stars': 45,
                'min_wpm_4stars': 60,
                'min_wpm_5stars': 80,
            },
            {
                'level_number': 12,
                'stage': 'speed_training',
                'level_title': 'Stage 12: Speed Training',
                'lesson_number': 51,
                'title': 'Velocity Sprint 3: The 80 WPM Barrier',
                'slug': 'velocity-sprint-3',
                'key_name': '80 WPM Barrier Drill',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Breaking through the elite 80 WPM barrier with light, feather-touch keystrokes.',
                'skill_learned': 'Feather-touch high speed stroke technique.',
                'spaced_repetition_keys': 'full keyboard',
                'learning_objective': 'Goal: Break through the professional typist speed barrier with feather-light keystrokes.',
                'instruction': 'Keep breathing steady and fingers light as feathers.',
                'target_text': 'Speed emerges naturally when accuracy becomes second nature and each keystroke flows into the next without friction or doubt.',
                'keys_introduced': 'speed sprint',
                'min_wpm_3stars': 48,
                'min_wpm_4stars': 65,
                'min_wpm_5stars': 85,
            },

            # LEVEL 13: ACCURACY TRAINING (Lessons 52 - 54)
            {
                'level_number': 13,
                'stage': 'accuracy_training',
                'level_title': 'Stage 13: Precision Mastery',
                'lesson_number': 52,
                'title': 'Precision Drill: Subtle Confusions',
                'slug': 'precision-subtle-confusions',
                'key_name': 'Subtle Key Distinctions',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Eliminates confusion between adjacent keys like e/r, i/o, b/v, n/m.',
                'skill_learned': 'Error eradication on easily confused keys.',
                'spaced_repetition_keys': 'e, r, i, o, b, v, n, m',
                'learning_objective': 'Goal: Eliminate errors between commonly confused keys with deliberate focus.',
                'instruction': 'Slow down slightly to achieve 99% or 100% accuracy.',
                'target_text': 'remember: believe, receive, weird, neighbor, achieve, perceive, deceit, conceit, neither, foreign, sovereign.',
                'keys_introduced': 'accuracy drill',
                'min_wpm_3stars': 35,
                'min_wpm_4stars': 48,
                'min_wpm_5stars': 65,
            },
            {
                'level_number': 13,
                'stage': 'accuracy_training',
                'level_title': 'Stage 13: Precision Mastery',
                'lesson_number': 53,
                'title': 'The Zero Mistake Challenge',
                'slug': 'zero-mistake-challenge',
                'key_name': 'Zero Mistake Gauntlet',
                'target_finger': 'All Fingers',
                'finger_hand': 'Both Hands',
                'finger_why': 'Proves unshakeable discipline and zero-error touch typing precision.',
                'skill_learned': 'Flawless precision under pressure.',
                'spaced_repetition_keys': 'all alphabet and punctuation',
                'learning_objective': 'Goal: Complete an intricate passage with zero uncorrected errors.',
                'instruction': 'Accuracy is king. True speed is impossible without precision.',
                'target_text': 'Precision typing demands discipline, patience, and deliberate focus. Every correct strike reinforces neural pathways that will serve you for a lifetime.',
                'keys_introduced': 'accuracy drill',
                'min_wpm_3stars': 38,
                'min_wpm_4stars': 50,
                'min_wpm_5stars': 70,
            },
            {
                'level_number': 13,
                'stage': 'accuracy_training',
                'level_title': 'Stage 13: Precision Mastery',
                'lesson_number': 54,
                'title': 'The Grandmaster Graduation',
                'slug': 'grandmaster-graduation',
                'key_name': 'TypeForge Graduation',
                'target_finger': 'All Fingers (Complete Master)',
                'finger_hand': 'Both Hands',
                'finger_why': 'Synthesizes letters, numbers, capitals, symbols, and punctuation into complete touch-typing mastery.',
                'skill_learned': 'Elite touch-typing mastery (top 5% global competence).',
                'spaced_repetition_keys': 'full keyboard (letters, numbers, symbols)',
                'learning_objective': 'Goal: Graduate from TypeForge as an elite touch typist with 60+ WPM and 95%+ accuracy.',
                'instruction': 'This is your capstone challenge. Combine speed, accuracy, numbers, and symbols.',
                'target_text': 'Congratulations! By mastering touch typing on TypeForge, you have joined the top 5% of computer users worldwide: typing at 60+ WPM with over 95% accuracy!',
                'keys_introduced': 'capstone',
                'min_wpm_3stars': 40,
                'min_wpm_4stars': 55,
                'min_wpm_5stars': 75,
            },
        ]

        for l_data in lessons_data:
            Lesson.objects.update_or_create(
                course=course,
                lesson_number=l_data['lesson_number'],
                defaults=l_data
            )

        self.stdout.write(self.style.SUCCESS(f"Updated all {len(lessons_data)} lessons with full pedagogical data!"))
