from django.core.management.base import BaseCommand
from core.models import Course, Lesson, Achievement

class Command(BaseCommand):
    help = 'Seeds TypeForge curriculum with 13 progressive levels, 54 lessons, and achievements'

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding TypeForge curriculum..."))

        course, created = Course.objects.get_or_create(
            slug='touch-typing-mastery',
            defaults={
                'title': 'Touch Typing Mastery',
                'description': 'Master touch typing step-by-step from home row foundation to advanced speed and precision.',
                'icon': 'keyboard',
                'order': 1
            }
        )
        if created:
            self.stdout.write(self.style.SUCCESS(f"Created course: {course.title}"))
        else:
            self.stdout.write(f"Using existing course: {course.title}")

        # 54 comprehensive progressive lessons
        lessons_data = [
            # LEVEL 1: Getting Started
            {
                'level_number': 1,
                'level_title': 'Level 1: Getting Started',
                'lesson_number': 1,
                'title': 'Introduction to the Home Row',
                'slug': 'intro-home-row',
                'learning_objective': 'Learn correct posture, hand resting position, and find the index bumps on F and J.',
                'instruction': 'Place your left index finger on F and right index finger on J. Feel the small raised ridges. Rest lightly without pressing down.',
                'target_text': 'f j f j f j f j ff jj ff jj',
                'keys_introduced': 'f, j',
                'min_wpm_3stars': 10,
                'min_wpm_4stars': 18,
                'min_wpm_5stars': 25,
            },
            {
                'level_number': 1,
                'level_title': 'Level 1: Getting Started',
                'lesson_number': 2,
                'title': 'The F and J Keys',
                'slug': 'f-and-j-keys',
                'learning_objective': 'Develop muscle memory for striking F with the left index finger and J with the right index finger.',
                'instruction': 'Press F with your left index finger and J with your right index finger. Keep your wrists relaxed and floating slightly above the desk.',
                'target_text': 'fj jf fj jf ff jj fj jf ff jj fj jf jf fj',
                'keys_introduced': 'f, j',
                'min_wpm_3stars': 12,
                'min_wpm_4stars': 20,
                'min_wpm_5stars': 28,
            },
            {
                'level_number': 1,
                'level_title': 'Level 1: Getting Started',
                'lesson_number': 3,
                'title': 'Alternating F and J Rhythm',
                'slug': 'alternating-f-and-j',
                'learning_objective': 'Build an even cadence between both hands.',
                'instruction': 'Focus on an even beat like a clock ticking. Do not rush; aim for 100% accuracy.',
                'target_text': 'f f j j f j f j j f j f ff jj jf fj ff jj',
                'keys_introduced': 'f, j',
                'min_wpm_3stars': 14,
                'min_wpm_4stars': 22,
                'min_wpm_5stars': 30,
            },
            {
                'level_number': 1,
                'level_title': 'Level 1: Getting Started',
                'lesson_number': 4,
                'title': 'The Space Bar',
                'slug': 'the-space-bar',
                'learning_objective': 'Integrate the space bar using your right or left thumb.',
                'instruction': 'Tap the space bar gently with whichever thumb feels natural. Return immediately to the home position.',
                'target_text': 'f j f j fj jf ff jj j j f f fj jf f j f j',
                'keys_introduced': 'space',
                'min_wpm_3stars': 15,
                'min_wpm_4stars': 24,
                'min_wpm_5stars': 32,
            },

            # LEVEL 2: Home Row
            {
                'level_number': 2,
                'level_title': 'Level 2: Home Row Mastery',
                'lesson_number': 5,
                'title': 'D and K Keys',
                'slug': 'd-and-k-keys',
                'learning_objective': 'Master left middle finger for D and right middle finger for K.',
                'instruction': 'Use your left middle finger for D, and right middle finger for K. Keep your index fingers anchored on F and J.',
                'target_text': 'd k d k dk kd dd kk df jk kd fd dk kd fk jd',
                'keys_introduced': 'd, k',
                'min_wpm_3stars': 15,
                'min_wpm_4stars': 24,
                'min_wpm_5stars': 32,
            },
            {
                'level_number': 2,
                'level_title': 'Level 2: Home Row Mastery',
                'lesson_number': 6,
                'title': 'F, J, D, and K Combinations',
                'slug': 'f-j-d-k-combos',
                'learning_objective': 'Coordinate index and middle fingers together across hands.',
                'instruction': 'Keep all fingers curved gently. Press directly downward with the finger pads.',
                'target_text': 'kfd jdf djk fkd dff kjj ddk kkf jfd kdf djk',
                'keys_introduced': 'd, k, f, j',
                'min_wpm_3stars': 16,
                'min_wpm_4stars': 25,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 2,
                'level_title': 'Level 2: Home Row Mastery',
                'lesson_number': 7,
                'title': 'S and L Keys',
                'slug': 's-and-l-keys',
                'learning_objective': 'Develop strength and coordination in your ring fingers.',
                'instruction': 'Use your left ring finger for S and right ring finger for L.',
                'target_text': 's l s l sl ls ss ll as df jk l; sk dl ls sl',
                'keys_introduced': 's, l',
                'min_wpm_3stars': 16,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 2,
                'level_title': 'Level 2: Home Row Mastery',
                'lesson_number': 8,
                'title': 'A and Semicolon Keys',
                'slug': 'a-and-semicolon',
                'learning_objective': 'Train your pinky fingers for A and Semicolon on the outer edges.',
                'instruction': 'Use your left pinky for A and right pinky for semicolon (;). Do not rotate your wrist outward.',
                'target_text': 'a ; a ; a; ;a aa ;; as df jk l; a; fa ja ;a',
                'keys_introduced': 'a, ;',
                'min_wpm_3stars': 16,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 2,
                'level_title': 'Level 2: Home Row Mastery',
                'lesson_number': 9,
                'title': 'Home Row Complete Flow',
                'slug': 'home-row-flow',
                'learning_objective': 'Integrate all eight home row keys seamlessly.',
                'instruction': 'All fingers are now active on the home row: A S D F and J K L ;',
                'target_text': 'asdf jkl; asdf jkl; a s d f j k l ; sad lad fad ask all',
                'keys_introduced': 'a, s, d, f, j, k, l, ;',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },
            {
                'level_number': 2,
                'level_title': 'Level 2: Home Row Mastery',
                'lesson_number': 10,
                'title': 'Home Row Words',
                'slug': 'home-row-words',
                'learning_objective': 'Type real English words created solely from home row keys.',
                'instruction': 'Read the whole word in your mind before pressing the keys.',
                'target_text': 'ask all fall lad dad sad flask salad salsa flash falls alas',
                'keys_introduced': 'home row words',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },

            # LEVEL 3: Top Row
            {
                'level_number': 3,
                'level_title': 'Level 3: Top Row',
                'lesson_number': 11,
                'title': 'G and H Keys',
                'slug': 'g-and-h-keys',
                'learning_objective': 'Reach inward to G with left index and H with right index.',
                'instruction': 'Stretch your index fingers slightly inward toward the center to reach G and H, then return to F and J.',
                'target_text': 'fg hj gf jh gg hh fg hj gaga haha glad half flag shaft dash',
                'keys_introduced': 'g, h',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },
            {
                'level_number': 3,
                'level_title': 'Level 3: Top Row',
                'lesson_number': 12,
                'title': 'R and U Keys',
                'slug': 'r-and-u-keys',
                'learning_objective': 'Reach up from F to R, and up from J to U.',
                'instruction': 'Reach your left index up to R, and your right index up to U. Always snap back to home position.',
                'target_text': 'fr ju rf uj rr uu fur jug jar run rug rust dust surf guard',
                'keys_introduced': 'r, u',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'level_title': 'Level 3: Top Row',
                'lesson_number': 13,
                'title': 'E and I Keys',
                'slug': 'e-and-i-keys',
                'learning_objective': 'Reach up from D to E, and up from K to I.',
                'instruction': 'Use left middle for E and right middle for I. E and I are two of the most common vowels in English.',
                'target_text': 'de ki ed ik ee ii ride side like fire hide life deer risk side',
                'keys_introduced': 'e, i',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'level_title': 'Level 3: Top Row',
                'lesson_number': 14,
                'title': 'W and O Keys',
                'slug': 'w-and-o-keys',
                'learning_objective': 'Reach up from S to W, and up from L to O.',
                'instruction': 'Use left ring finger for W, right ring finger for O.',
                'target_text': 'sw lo ws ol ww oo show slow wolf wood word flow work good',
                'keys_introduced': 'w, o',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'level_title': 'Level 3: Top Row',
                'lesson_number': 15,
                'title': 'Q and P Keys',
                'slug': 'q-and-p-keys',
                'learning_objective': 'Reach up from A to Q, and up from semicolon to P.',
                'instruction': 'Reach your left pinky up to Q, and your right pinky up to P.',
                'target_text': 'aq ;p qa p; qq pp equip quote paper power quick park proud',
                'keys_introduced': 'q, p',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 3,
                'level_title': 'Level 3: Top Row',
                'lesson_number': 16,
                'title': 'Top Row Words & Integration',
                'slug': 'top-row-words',
                'learning_objective': 'Synthesize top row and home row letters smoothly.',
                'instruction': 'Flow smoothly through words combining both rows.',
                'target_text': 'pure quiet quiet pride tower write water power guide report sleep',
                'keys_introduced': 'q, w, e, r, t, y, u, i, o, p',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },

            # LEVEL 4: Bottom Row
            {
                'level_number': 4,
                'level_title': 'Level 4: Bottom Row',
                'lesson_number': 17,
                'title': 'V and M Keys',
                'slug': 'v-and-m-keys',
                'learning_objective': 'Reach down from F to V, and down from J to M.',
                'instruction': 'Left index finger moves down and right to V. Right index finger moves down and left to M.',
                'target_text': 'fv jm vf mj vv mm vine move view move voice vim form norm',
                'keys_introduced': 'v, m',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'level_title': 'Level 4: Bottom Row',
                'lesson_number': 18,
                'title': 'C and Comma Keys',
                'slug': 'c-and-comma',
                'learning_objective': 'Reach down from D to C, and down from K to comma (,).',
                'instruction': 'Left middle reaches down to C. Right middle reaches down to comma (,).',
                'target_text': 'dc k, cd ,k cc ,, come, call, calm, cool, camp, code, pace,',
                'keys_introduced': 'c, ,',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'level_title': 'Level 4: Bottom Row',
                'lesson_number': 19,
                'title': 'X and Period Keys',
                'slug': 'x-and-period',
                'learning_objective': 'Reach down from S to X, and down from L to period (.).',
                'instruction': 'Left ring finger moves down to X. Right ring finger moves down to period (.).',
                'target_text': 'sx l. xs .l xx .. exact. exam. extra. next. text. fix. mix.',
                'keys_introduced': 'x, .',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'level_title': 'Level 4: Bottom Row',
                'lesson_number': 20,
                'title': 'Z and Slash Keys',
                'slug': 'z-and-slash',
                'learning_objective': 'Reach down from A to Z, and down from semicolon to slash (/).',
                'instruction': 'Left pinky reaches down to Z. Right pinky reaches down to slash (/).',
                'target_text': 'az ;/ za /; zz // zero/zone jazz/zoom zinc/zeal size/maze',
                'keys_introduced': 'z, /',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 4,
                'level_title': 'Level 4: Bottom Row',
                'lesson_number': 21,
                'title': 'Bottom Row Integration',
                'slug': 'bottom-row-integration',
                'learning_objective': 'Type sentences utilizing bottom row punctuation and characters.',
                'instruction': 'Keep wrists steady as fingers reach down.',
                'target_text': 'vocal calm exact zone. move quick, view text, zinc maze.',
                'keys_introduced': 'z, x, c, v, m, ,, ., /',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },

            # LEVEL 5: Full Alphabet
            {
                'level_number': 5,
                'level_title': 'Level 5: Full Alphabet Integration',
                'lesson_number': 22,
                'title': 'Every Letter Connected',
                'slug': 'every-letter-connected',
                'learning_objective': 'Connect words spanning all 26 lowercase letters.',
                'instruction': 'Maintain a steady typing pace. Do not look down at the keyboard.',
                'target_text': 'the quick brown fox jumps over a lazy dog while walking near',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 24,
                'min_wpm_4stars': 34,
                'min_wpm_5stars': 45,
            },
            {
                'level_number': 5,
                'level_title': 'Level 5: Full Alphabet Integration',
                'lesson_number': 23,
                'title': 'Pangram Precision',
                'slug': 'pangram-precision',
                'learning_objective': 'Reinforce dexterity with famous English pangrams.',
                'instruction': 'A pangram contains every letter of the alphabet at least once.',
                'target_text': 'pack my box with five dozen liquor jugs and cozy warm blankets',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 25,
                'min_wpm_4stars': 35,
                'min_wpm_5stars': 46,
            },
            {
                'level_number': 5,
                'level_title': 'Level 5: Full Alphabet Integration',
                'lesson_number': 24,
                'title': 'Alphabet Speed Flow',
                'slug': 'alphabet-speed-flow',
                'learning_objective': 'Fluid movement between adjacent and opposite hand strikes.',
                'instruction': 'Focus on muscle relaxation and rhythm.',
                'target_text': 'how vexingly quick daft zebras jump through foggy twilight skies',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 26,
                'min_wpm_4stars': 36,
                'min_wpm_5stars': 48,
            },
            {
                'level_number': 5,
                'level_title': 'Level 5: Full Alphabet Integration',
                'lesson_number': 25,
                'title': 'Full Alphabet Milestone',
                'slug': 'alphabet-milestone',
                'learning_objective': 'Demonstrate mastery of all 26 lowercase letters.',
                'instruction': 'Test your complete keyboard coverage without stopping.',
                'target_text': 'bright vixens jump safely with quiet quick zeal and nimble grace',
                'keys_introduced': 'all alphabet',
                'min_wpm_3stars': 28,
                'min_wpm_4stars': 38,
                'min_wpm_5stars': 50,
            },

            # LEVEL 6: Capital Letters & Shift Keys
            {
                'level_number': 6,
                'level_title': 'Level 6: Capital Letters & Shift Keys',
                'lesson_number': 26,
                'title': 'Right Shift with Left Hand Keys',
                'slug': 'right-shift-left-hand',
                'learning_objective': 'Use right pinky on Right Shift when typing left hand capitals.',
                'instruction': 'Press and hold Right Shift with your right pinky while typing A, S, D, F, Q, W, E, R, T, G, Z, X, C, V.',
                'target_text': 'Fast Deer Slow Fox Red Water Green Eagle Clean Quiet Travel',
                'keys_introduced': 'Right Shift',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },
            {
                'level_number': 6,
                'level_title': 'Level 6: Capital Letters & Shift Keys',
                'lesson_number': 27,
                'title': 'Left Shift with Right Hand Keys',
                'slug': 'left-shift-right-hand',
                'learning_objective': 'Use left pinky on Left Shift when typing right hand capitals.',
                'instruction': 'Press and hold Left Shift with your left pinky while typing J, K, L, Y, U, I, O, P, H, N, M.',
                'target_text': 'Jump Kite Lake Moon Hope Peak Night Island Yellow Olive Path',
                'keys_introduced': 'Left Shift',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 32,
                'min_wpm_5stars': 42,
            },
            {
                'level_number': 6,
                'level_title': 'Level 6: Capital Letters & Shift Keys',
                'lesson_number': 28,
                'title': 'Proper Names & Cities',
                'slug': 'proper-names-cities',
                'learning_objective': 'Alternate left and right shift keys naturally.',
                'instruction': 'Always use the shift key on the opposite hand of the letter you are typing.',
                'target_text': 'London, Paris, Tokyo, Berlin, Madrid, Chicago, Sydney, Oslo, Rome',
                'keys_introduced': 'Shift alternation',
                'min_wpm_3stars': 24,
                'min_wpm_4stars': 34,
                'min_wpm_5stars': 45,
            },
            {
                'level_number': 6,
                'level_title': 'Level 6: Capital Letters & Shift Keys',
                'lesson_number': 29,
                'title': 'Capitalized Sentences',
                'slug': 'capitalized-sentences',
                'learning_objective': 'Type standard English sentences starting with capitals.',
                'instruction': 'Strike the capital smoothly, then continue lowercase typing.',
                'target_text': 'Every journey begins with a single step. Practice makes permanent.',
                'keys_introduced': 'Sentence capitalization',
                'min_wpm_3stars': 25,
                'min_wpm_4stars': 35,
                'min_wpm_5stars': 46,
            },

            # LEVEL 7: Numbers
            {
                'level_number': 7,
                'level_title': 'Level 7: Numbers Row',
                'lesson_number': 30,
                'title': 'Left Hand Numbers (1, 2, 3, 4, 5)',
                'slug': 'left-hand-numbers',
                'learning_objective': 'Reach up two rows from home to strike numbers 1 through 5.',
                'instruction': 'Pinky for 1, Ring for 2, Middle for 3, Index for 4 and 5.',
                'target_text': '1 2 3 4 5 12 34 51 25 43 15 24 35 123 451 234 521',
                'keys_introduced': '1, 2, 3, 4, 5',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 7,
                'level_title': 'Level 7: Numbers Row',
                'lesson_number': 31,
                'title': 'Right Hand Numbers (6, 7, 8, 9, 0)',
                'slug': 'right-hand-numbers',
                'learning_objective': 'Reach up to strike numbers 6 through 0 with your right hand.',
                'instruction': 'Index for 6 and 7, Middle for 8, Ring for 9, Pinky for 0.',
                'target_text': '6 7 8 9 0 67 89 06 78 90 68 79 80 678 901 890 760',
                'keys_introduced': '6, 7, 8, 9, 0',
                'min_wpm_3stars': 18,
                'min_wpm_4stars': 26,
                'min_wpm_5stars': 35,
            },
            {
                'level_number': 7,
                'level_title': 'Level 7: Numbers Row',
                'lesson_number': 32,
                'title': 'Numbers in Real Sentences',
                'slug': 'numbers-in-sentences',
                'learning_objective': 'Seamlessly transition between letters and numbers.',
                'instruction': 'Keep your home position anchored in your minds eye.',
                'target_text': 'In 1995 there were 32 computers, by 2024 there were over 870 devices.',
                'keys_introduced': 'numbers in context',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },

            # LEVEL 8: Symbols & Punctuation
            {
                'level_number': 8,
                'level_title': 'Level 8: Symbols & Punctuation',
                'lesson_number': 33,
                'title': 'Exclamation and Question Marks',
                'slug': 'exclamation-and-question',
                'learning_objective': 'Master Shift + 1 (!) and Shift + / (?).',
                'instruction': 'Right Shift + 1 for !, Left Shift + / for ?.',
                'target_text': 'Hello! Is this working? Yes! Are you ready? Great! Let us start!',
                'keys_introduced': '!, ?',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 8,
                'level_title': 'Level 8: Symbols & Punctuation',
                'lesson_number': 34,
                'title': 'Quotes and Apostrophes',
                'slug': 'quotes-and-apostrophes',
                'learning_objective': 'Type contractions and quotations with speed and accuracy.',
                'instruction': 'Apostrophe is typed with the right pinky next to the enter key.',
                'target_text': 'She said, "Do not worry, it\'s going to be fine." We can\'t stop now.',
                'keys_introduced': '\', "',
                'min_wpm_3stars': 22,
                'min_wpm_4stars': 30,
                'min_wpm_5stars': 40,
            },
            {
                'level_number': 8,
                'level_title': 'Level 8: Symbols & Punctuation',
                'lesson_number': 35,
                'title': 'Brackets and Parentheses',
                'slug': 'brackets-and-parentheses',
                'learning_objective': 'Type ( ), [ ], and { } commonly used in writing and code.',
                'instruction': 'Use Shift + 9 and 0 for parentheses. Use bracket keys near P.',
                'target_text': 'The function calculate(x, y) returns [result] with options {fast: true}.',
                'keys_introduced': '(, ), [, ], {, }',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },
            {
                'level_number': 8,
                'level_title': 'Level 8: Symbols & Punctuation',
                'lesson_number': 36,
                'title': 'Special Symbols & Math',
                'slug': 'special-symbols-math',
                'learning_objective': 'Handle currency, percentages, email signs, and math operators.',
                'instruction': 'Shift across the number row: @, #, $, %, &, *, +, =.',
                'target_text': 'Save 25% today! Contact user@example.com for $50 + $10 bonus.',
                'keys_introduced': '@, #, $, %, &, *, +, =',
                'min_wpm_3stars': 20,
                'min_wpm_4stars': 28,
                'min_wpm_5stars': 38,
            },

            # LEVEL 9: Common Words
            {
                'level_number': 9,
                'level_title': 'Level 9: Common Words',
                'lesson_number': 37,
                'title': 'Top 25 Most Common Words',
                'slug': 'top-25-words',
                'learning_objective': 'Automate typing of the most frequent words in the English language.',
                'instruction': 'Type entire words as single muscle memory chords.',
                'target_text': 'the of and a to in is you that it he was for on are as with his they at be this have from or',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 28,
                'min_wpm_4stars': 38,
                'min_wpm_5stars': 50,
            },
            {
                'level_number': 9,
                'level_title': 'Level 9: Common Words',
                'lesson_number': 38,
                'title': 'Words 26 through 50',
                'slug': 'words-26-to-50',
                'learning_objective': 'Increase typing velocity through familiar word patterns.',
                'instruction': 'Notice letter groupings like "th", "ing", "ed", and "er".',
                'target_text': 'one had by word but not what all were we when your can said there use an each which she do how their if will',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 30,
                'min_wpm_4stars': 40,
                'min_wpm_5stars': 52,
            },
            {
                'level_number': 9,
                'level_title': 'Level 9: Common Words',
                'lesson_number': 39,
                'title': 'Words 51 through 75',
                'slug': 'words-51-to-75',
                'learning_objective': 'Build stamina across mid-frequency vocabulary.',
                'instruction': 'Keep a relaxed rhythm without pausing between words.',
                'target_text': 'up other about out many then them these so some her would make like him into time has look two more write go see',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 30,
                'min_wpm_4stars': 40,
                'min_wpm_5stars': 52,
            },
            {
                'level_number': 9,
                'level_title': 'Level 9: Common Words',
                'lesson_number': 40,
                'title': 'Words 76 through 100',
                'slug': 'words-76-to-100',
                'learning_objective': 'Complete the top 100 words which make up over 50% of written English.',
                'instruction': 'Mastering these 100 words unlocks automatic touch typing.',
                'target_text': 'number no way could people my than first water been call who oil its now find long down day did get come made may part',
                'keys_introduced': 'frequency drill',
                'min_wpm_3stars': 32,
                'min_wpm_4stars': 42,
                'min_wpm_5stars': 55,
            },

            # LEVEL 10: Sentences & Flow
            {
                'level_number': 10,
                'level_title': 'Level 10: Sentences & Flow',
                'lesson_number': 41,
                'title': 'Short Conversational Sentences',
                'slug': 'conversational-sentences',
                'learning_objective': 'Type flowing everyday sentences with proper capitalization and periods.',
                'instruction': 'Read ahead of your fingers by two words.',
                'target_text': 'The sun rises in the east every morning. A cool breeze moved across the silent valley.',
                'keys_introduced': 'sentence flow',
                'min_wpm_3stars': 30,
                'min_wpm_4stars': 42,
                'min_wpm_5stars': 55,
            },
            {
                'level_number': 10,
                'level_title': 'Level 10: Sentences & Flow',
                'lesson_number': 42,
                'title': 'Descriptive Observations',
                'slug': 'descriptive-observations',
                'learning_objective': 'Balance varied punctuation with descriptive text.',
                'instruction': 'Stay focused on consistent tempo.',
                'target_text': 'Clear blue water flowed gently over the smooth river stones, reflecting the golden sunlight.',
                'keys_introduced': 'sentence flow',
                'min_wpm_3stars': 32,
                'min_wpm_4stars': 44,
                'min_wpm_5stars': 58,
            },
            {
                'level_number': 10,
                'level_title': 'Level 10: Sentences & Flow',
                'lesson_number': 43,
                'title': 'Dialogue & Interrogatives',
                'slug': 'dialogue-interrogatives',
                'learning_objective': 'Mix quotation marks, question marks, and conversational phrasing.',
                'instruction': 'Use correct pinky coordination for quotes.',
                'target_text': '"Where are we heading next?" asked Maya with a bright smile. "To the mountain peak!"',
                'keys_introduced': 'dialogue flow',
                'min_wpm_3stars': 32,
                'min_wpm_4stars': 44,
                'min_wpm_5stars': 58,
            },
            {
                'level_number': 10,
                'level_title': 'Level 10: Sentences & Flow',
                'lesson_number': 44,
                'title': 'Continuous Thought Flow',
                'slug': 'continuous-thought-flow',
                'learning_objective': 'Develop prolonged typing without mental fatigue.',
                'instruction': 'Breathe steadily while typing longer passages.',
                'target_text': 'Curiosity drives discoveries that reshape the future, turning ambitious dreams into everyday reality.',
                'keys_introduced': 'sentence flow',
                'min_wpm_3stars': 34,
                'min_wpm_4stars': 46,
                'min_wpm_5stars': 60,
            },

            # LEVEL 11: Paragraphs & Literature
            {
                'level_number': 11,
                'level_title': 'Level 11: Paragraphs & Literature',
                'lesson_number': 45,
                'title': 'The Craft of Writing',
                'slug': 'the-craft-of-writing',
                'learning_objective': 'Engage with sustained long-form prose.',
                'instruction': 'Do not rush early sentences. Establish a sustainable cruising speed.',
                'target_text': 'Writing is the painting of the voice. Through words, human beings bridge vast oceans of time and thought, sharing wisdom across generations with timeless clarity and emotional resonance.',
                'keys_introduced': 'paragraph flow',
                'min_wpm_3stars': 35,
                'min_wpm_4stars': 48,
                'min_wpm_5stars': 62,
            },
            {
                'level_number': 11,
                'level_title': 'Level 11: Paragraphs & Literature',
                'lesson_number': 46,
                'title': 'The Origins of the Keyboard',
                'slug': 'origins-of-the-keyboard',
                'learning_objective': 'Type informative historical text with complex terms.',
                'instruction': 'Keep posture upright and shoulders relaxed.',
                'target_text': 'The QWERTY keyboard layout was engineered in the late nineteenth century to prevent mechanical typebars from colliding. Over a century later, touch typing remains the primary interface between human creativity and digital machines.',
                'keys_introduced': 'history prose',
                'min_wpm_3stars': 36,
                'min_wpm_4stars': 50,
                'min_wpm_5stars': 64,
            },
            {
                'level_number': 11,
                'level_title': 'Level 11: Paragraphs & Literature',
                'lesson_number': 47,
                'title': 'Mountain Reflections',
                'slug': 'mountain-reflections',
                'learning_objective': 'Type vivid literary prose with varied rhythm.',
                'instruction': 'Observe how natural punctuation creates pauses in your typing rhythm.',
                'target_text': 'High above the treeline, alpine peaks caught the first rays of dawn. Cold winds whispered through ancient granite cliffs, while below, clouds drifted like soft waves over quiet valleys.',
                'keys_introduced': 'literary prose',
                'min_wpm_3stars': 36,
                'min_wpm_4stars': 50,
                'min_wpm_5stars': 65,
            },
            {
                'level_number': 11,
                'level_title': 'Level 11: Paragraphs & Literature',
                'lesson_number': 48,
                'title': 'Deep Ocean Depths',
                'slug': 'deep-ocean-depths',
                'learning_objective': 'Maintain high endurance across descriptive science literature.',
                'instruction': 'Keep mistakes under control. Aim for 98%+ accuracy.',
                'target_text': 'Beneath the surface of the open sea lies a world of silence and wonder. Bioluminescent creatures glow in the abyssal darkness, navigating currents that have traveled around the globe for thousands of years.',
                'keys_introduced': 'science prose',
                'min_wpm_3stars': 38,
                'min_wpm_4stars': 52,
                'min_wpm_5stars': 68,
            },

            # LEVEL 12: Speed Training
            {
                'level_number': 12,
                'level_title': 'Level 12: Speed Sprints',
                'lesson_number': 49,
                'title': 'Velocity Sprint 1: Rapid Words',
                'slug': 'velocity-sprint-1',
                'learning_objective': 'Push your speed threshold on quick, punchy vocabulary.',
                'instruction': 'Let your fingers fly! Test your maximum raw speed.',
                'target_text': 'go fast run quick leap dash swift bolt sprint speed rush flash zoom drive fly glide soar blaze rocket surge dart race',
                'keys_introduced': 'speed sprint',
                'min_wpm_3stars': 42,
                'min_wpm_4stars': 58,
                'min_wpm_5stars': 75,
            },
            {
                'level_number': 12,
                'level_title': 'Level 12: Speed Sprints',
                'lesson_number': 50,
                'title': 'Velocity Sprint 2: High Cadence',
                'slug': 'velocity-sprint-2',
                'learning_objective': 'Maintain rapid typing without hesitating on word transitions.',
                'instruction': 'Zero hesitation between space bars.',
                'target_text': 'rapid motion brings agile results when hands operate with confidence, clarity, and relentless forward determination.',
                'keys_introduced': 'speed sprint',
                'min_wpm_3stars': 45,
                'min_wpm_4stars': 60,
                'min_wpm_5stars': 80,
            },
            {
                'level_number': 12,
                'level_title': 'Level 12: Speed Sprints',
                'lesson_number': 51,
                'title': 'Velocity Sprint 3: The 80 WPM Barrier',
                'slug': 'velocity-sprint-3',
                'learning_objective': 'Break through the professional typist speed barrier.',
                'instruction': 'Keep breathing steady and fingers light as feathers.',
                'target_text': 'Speed emerges naturally when accuracy becomes second nature and each keystroke flows into the next without friction or doubt.',
                'keys_introduced': 'speed sprint',
                'min_wpm_3stars': 48,
                'min_wpm_4stars': 65,
                'min_wpm_5stars': 85,
            },

            # LEVEL 13: Accuracy Training
            {
                'level_number': 13,
                'level_title': 'Level 13: Precision Mastery',
                'lesson_number': 52,
                'title': 'Precision Drill: Subtle Confusions',
                'slug': 'precision-subtle-confusions',
                'learning_objective': 'Eliminate errors between commonly confused keys (e.g. e/r, i/o, b/v, n/m).',
                'instruction': 'Slow down slightly to achieve 99% or 100% accuracy.',
                'target_text': 'remember: believe, receive, weird, neighbor, achieve, perceive, deceit, conceit, neither, foreign, sovereign.',
                'keys_introduced': 'accuracy drill',
                'min_wpm_3stars': 35,
                'min_wpm_4stars': 48,
                'min_wpm_5stars': 65,
            },
            {
                'level_number': 13,
                'level_title': 'Level 13: Precision Mastery',
                'lesson_number': 53,
                'title': 'The Zero Mistake Challenge',
                'slug': 'zero-mistake-challenge',
                'learning_objective': 'Complete an intricate passage with zero uncorrected errors.',
                'instruction': 'Accuracy is king. True speed is impossible without precision.',
                'target_text': 'Precision typing demands discipline, patience, and deliberate focus. Every correct strike reinforces neural pathways that will serve you for a lifetime.',
                'keys_introduced': 'accuracy drill',
                'min_wpm_3stars': 38,
                'min_wpm_4stars': 50,
                'min_wpm_5stars': 70,
            },
            {
                'level_number': 13,
                'level_title': 'Level 13: Precision Mastery',
                'lesson_number': 54,
                'title': 'The Grandmaster Graduation',
                'slug': 'grandmaster-graduation',
                'learning_objective': 'Graduate from TypeForge as an elite touch typist.',
                'instruction': 'This is your capstone challenge. Combine speed, accuracy, numbers, and symbols.',
                'target_text': 'Congratulations! By mastering touch typing on TypeForge, you have joined the top 5% of computer users worldwide: typing at 60+ WPM with over 95% accuracy!',
                'keys_introduced': 'capstone',
                'min_wpm_3stars': 40,
                'min_wpm_4stars': 55,
                'min_wpm_5stars': 75,
            },
        ]

        created_lessons_count = 0
        for l_data in lessons_data:
            lesson, created = Lesson.objects.update_or_create(
                course=course,
                lesson_number=l_data['lesson_number'],
                defaults=l_data
            )
            if created:
                created_lessons_count += 1

        self.stdout.write(self.style.SUCCESS(f"Processed {len(lessons_data)} lessons ({created_lessons_count} newly created)."))

        # Achievements Data
        achievements_data = [
            {
                'code': 'first_lesson',
                'title': 'First Step',
                'description': 'Complete your very first typing lesson on TypeForge.',
                'category': 'lessons',
                'icon': 'play',
                'requirement_value': 1.0,
                'xp_reward': 50,
            },
            {
                'code': 'home_row_hero',
                'title': 'Home Row Hero',
                'description': 'Complete all 10 lessons of the Home Row modules.',
                'category': 'lessons',
                'icon': 'award',
                'requirement_value': 10.0,
                'xp_reward': 150,
            },
            {
                'code': 'ten_lessons',
                'title': 'Decade of Dedication',
                'description': 'Complete 10 distinct typing lessons.',
                'category': 'lessons',
                'icon': 'check-circle',
                'requirement_value': 10.0,
                'xp_reward': 150,
            },
            {
                'code': 'twenty_five_lessons',
                'title': 'Halfway Prodigy',
                'description': 'Complete 25 lessons across the curriculum.',
                'category': 'lessons',
                'icon': 'star',
                'requirement_value': 25.0,
                'xp_reward': 300,
            },
            {
                'code': 'course_graduate',
                'title': 'Grandmaster Typist',
                'description': 'Complete all 54 lessons and graduate touch typing mastery.',
                'category': 'lessons',
                'icon': 'crown',
                'requirement_value': 54.0,
                'xp_reward': 1000,
            },
            # Speed Category
            {
                'code': 'speed_30',
                'title': 'Quick Silver (30 WPM)',
                'description': 'Reach 30 WPM or higher on any lesson or typing test.',
                'category': 'speed',
                'icon': 'zap',
                'requirement_value': 30.0,
                'xp_reward': 100,
            },
            {
                'code': 'speed_50',
                'title': 'Velocity Pro (50 WPM)',
                'description': 'Reach 50 WPM or higher on any lesson or typing test.',
                'category': 'speed',
                'icon': 'wind',
                'requirement_value': 50.0,
                'xp_reward': 250,
            },
            {
                'code': 'speed_75',
                'title': 'Supersonic (75 WPM)',
                'description': 'Reach 75 WPM or higher on any lesson or typing test.',
                'category': 'speed',
                'icon': 'flame',
                'requirement_value': 75.0,
                'xp_reward': 500,
            },
            {
                'code': 'speed_100',
                'title': 'Century Speedster (100 WPM)',
                'description': 'Break the triple-digit barrier with 100+ WPM!',
                'category': 'speed',
                'icon': 'shield',
                'requirement_value': 100.0,
                'xp_reward': 1000,
            },
            # Accuracy Category
            {
                'code': 'accuracy_90',
                'title': 'Solid Hand (90% Accuracy)',
                'description': 'Finish a lesson with at least 90% accuracy.',
                'category': 'accuracy',
                'icon': 'target',
                'requirement_value': 90.0,
                'xp_reward': 75,
            },
            {
                'code': 'accuracy_95',
                'title': 'Sharpshooter (95% Accuracy)',
                'description': 'Finish a lesson with at least 95% accuracy.',
                'category': 'accuracy',
                'icon': 'crosshair',
                'requirement_value': 95.0,
                'xp_reward': 150,
            },
            {
                'code': 'accuracy_100',
                'title': 'Flawless Diamond (100% Accuracy)',
                'description': 'Complete a lesson with absolute 100% perfection.',
                'category': 'accuracy',
                'icon': 'gem',
                'requirement_value': 100.0,
                'xp_reward': 300,
            },
            # Streak Category
            {
                'code': 'streak_3',
                'title': 'Consistency Kickoff (3 Days)',
                'description': 'Practice typing 3 days in a row.',
                'category': 'streak',
                'icon': 'calendar',
                'requirement_value': 3.0,
                'xp_reward': 100,
            },
            {
                'code': 'streak_7',
                'title': 'Week Warrior (7 Days)',
                'description': 'Maintain an unbroken 7-day practice streak.',
                'category': 'streak',
                'icon': 'flame',
                'requirement_value': 7.0,
                'xp_reward': 300,
            },
            {
                'code': 'streak_30',
                'title': 'Iron Will (30 Days)',
                'description': 'Achieve a 30-day continuous daily streak.',
                'category': 'streak',
                'icon': 'sun',
                'requirement_value': 30.0,
                'xp_reward': 1000,
            },
            # Volume Category
            {
                'code': 'chars_1000',
                'title': 'Key Striker (1,000 Characters)',
                'description': 'Type over 1,000 characters on TypeForge.',
                'category': 'volume',
                'icon': 'type',
                'requirement_value': 1000.0,
                'xp_reward': 100,
            },
            {
                'code': 'chars_10000',
                'title': 'Typing Marathoner (10,000 Characters)',
                'description': 'Type over 10,000 characters total.',
                'category': 'volume',
                'icon': 'layers',
                'requirement_value': 10000.0,
                'xp_reward': 400,
            },
        ]

        created_achievements_count = 0
        for ach in achievements_data:
            obj, created = Achievement.objects.update_or_create(
                code=ach['code'],
                defaults=ach
            )
            if created:
                created_achievements_count += 1

        self.stdout.write(self.style.SUCCESS(f"Processed {len(achievements_data)} achievements ({created_achievements_count} newly created)."))
        self.stdout.write(self.style.SUCCESS("Curriculum and achievements successfully seeded!"))
