# Generated by Django 5.2.12 on 2026-09-16 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('lessons', 'Lessons & Learning'), ('speed', 'Typing Speed'), ('accuracy', 'Accuracy'), ('streak', 'Streaks & Consistency'), ('volume', 'Practice Volume')], default='lessons', max_length=20)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('requirement_value', models.FloatField(default=1.0)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='keyboard', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(db_index=True, default=1)),
                ('level_title', models.CharField(default='Level 1', max_length=100)),
                ('lesson_number', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('learning_objective', models.CharField(max_length=255)),
                ('instruction', models.TextField(help_text='Instructions shown to the user before or during typing')),
                ('target_text', models.TextField(help_text='The exact text the user must type')),
                ('keys_introduced', models.CharField(blank=True, help_text="e.g. 'f, j'", max_length=100)),
                ('min_wpm_3stars', models.PositiveIntegerField(default=15)),
                ('min_wpm_4stars', models.PositiveIntegerField(default=25)),
                ('min_wpm_5stars', models.PositiveIntegerField(default=35)),
                ('min_accuracy_threshold', models.FloatField(default=85.0, help_text='Minimum accuracy % to pass (1 star)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course')),
            ],
            options={
                'ordering': ['level_number', 'lesson_number'],
                'unique_together': {('course', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='TypingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('lesson', 'Lesson'), ('test', 'Typing Test'), ('game', 'Game'), ('practice', 'Free Practice')], default='lesson', max_length=20)),
                ('wpm', models.FloatField(default=0.0)),
                ('raw_wpm', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('mistakes_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('characters_typed', models.PositiveIntegerField(default=0)),
                ('key_mistakes', models.JSONField(blank=True, default=dict, help_text="Dict of character mistakes count, e.g. {'f': 3, 'j': 1}")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_mode', models.PositiveIntegerField(choices=[(30, '30 Seconds'), (60, '60 Seconds'), (120, '120 Seconds')], default=60)),
                ('wpm', models.FloatField(default=0.0)),
                ('raw_wpm', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('correct_chars', models.PositiveIntegerField(default=0)),
                ('incorrect_chars', models.PositiveIntegerField(default=0)),
                ('total_chars', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typing_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('total_practice_time_seconds', models.PositiveIntegerField(default=0)),
                ('avatar_color', models.CharField(default='#3b82f6', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_enabled', models.BooleanField(default=True)),
                ('keyboard_visible', models.BooleanField(default=True)),
                ('hand_guide_visible', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light Classic'), ('slate', 'Modern Slate'), ('dark', 'Dark Night')], default='slate', max_length=20)),
                ('instant_feedback', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('characters_typed', models.PositiveIntegerField(default=0)),
                ('practice_seconds', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('best_wpm', models.FloatField(default=0.0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'completed'], name='core_lesson_user_id_b74033_idx'), models.Index(fields=['user', 'lesson'], name='core_lesson_user_id_324053_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='core.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
