# Generated by Django 5.2.12 on 2026-09-16 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='finger_hand',
            field=models.CharField(default='Left & Right Hands', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='finger_why',
            field=models.TextField(default='Anchor your hands on the home row using the small physical ridges on F and J.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='key_name',
            field=models.CharField(default='Home Row Keys', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='min_mastery_accuracy',
            field=models.FloatField(default=90.0, help_text='Minimum accuracy % for mastery badge'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill_learned',
            field=models.CharField(default='Practiced correct finger placement and muscle memory.', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='spaced_repetition_keys',
            field=models.CharField(blank=True, help_text='Previously learned keys reinforced', max_length=150),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stage',
            field=models.CharField(choices=[('foundation', 'Foundation & Posture'), ('home_row', 'Home Row'), ('top_row', 'Top Row'), ('bottom_row', 'Bottom Row'), ('full_alphabet', 'Full Alphabet'), ('capital_letters', 'Capital Letters & Shift'), ('numbers', 'Numbers Row'), ('symbols', 'Symbols & Punctuation'), ('common_words', 'High Frequency Words'), ('sentences', 'Sentences & Flow'), ('paragraphs', 'Paragraphs & Literature'), ('speed_training', 'Speed Training'), ('accuracy_training', 'Accuracy Training')], db_index=True, default='home_row', max_length=30),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_finger',
            field=models.CharField(default='Index Fingers', max_length=100),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='mastery_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='min_accuracy_threshold',
            field=models.FloatField(default=85.0, help_text='Minimum accuracy % to complete (unlock next)'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'is_mastered'], name='core_lesson_user_id_6af2dd_idx'),
        ),
    ]
