# Generated by Django 5.2.12 on 2026-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
